kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1 
metadata:
  name: backupjob-role
rules:
- apiGroups: ["example.com.my.domain", "apiextensions.k8s.io"] 
  resources: ["backupjobs"] 
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete", "deletecollection"]
